### ISSUE TITLE
Cannot use .push

### ISSUE THREAD

**Issue by antononcube** [lizmat/Hash-str#1]
The following code :

```perl6
use Hash::str;
my %hash0 is Hash::str = fortytwo => "foo", sixsixsix => "bar";
%hash0.push: (fortyseven => 'new');
```

gives the error:

> Cannot resolve caller push(Hash::str: Pair:D); none of these signatures match:
>    (Any:U \SELF: |values) 
>    [...]

**Comment by lizmat** [comment]
Thanks for the report.  `.push` has been added with the latest release.
